const controlCenter=document.getElementById("controlCenter");const backToTopBtn=document.getElementById("backToTopBtn");const messengerBtn=document.getElementById("messengerBtn");const homeBtn=document.getElementById("homeBtn");const searchBtn=document.getElementById("searchBtn");backToTopBtn.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});function openMessenger(){window.open('http://m.me//playwiththomas','_blank')}
homeBtn.addEventListener('click',function(){window.location.href='index.html'});function focusInput(){const input=document.getElementById('searchInput');input.focus()}
function goBack(){window.history.back()}
const navEntries=performance.getEntriesByType("navigation");if(navEntries.length>0&&navEntries[0].type==="reload"){const baseUrl=window.location.href.split('?')[0];window.location.replace(`${baseUrl}?v=${Date.now()}`)}
function toggleMenu(){const navLinks=document.getElementById('navLinks');const header=document.querySelector("header");navLinks.classList.toggle('active');header.classList.toggle("menu-open");navLinks.classList.add('dropdown')}
let next=document.querySelector('.next');let prev=document.querySelector('.prev');let slider=document.querySelector('.slider');next.addEventListener('click',function(){let slide=document.querySelectorAll('.slide');slider.appendChild(slide[0])})
prev.addEventListener('click',function(){let slide=document.querySelectorAll('.slide');slider.prepend(slide[slide.length-1])})
const infoSlider=document.getElementById('infoSlider');const totalInfoSlides=infoSlider.children.length;let currentIndex=0;let interval=setInterval(nextSlide,3000);const infoNextBtn=document.getElementById('infoNextBtn');const infoPrevBtn=document.getElementById('infoPrevBtn');function updateSlider(){infoSlider.style.transform=`translateX(-${currentIndex * 100}%)`}
function nextSlide(){currentIndex=(currentIndex+1)%totalInfoSlides;updateSlider()}
function prevSlide(){currentIndex=(currentIndex-1+totalInfoSlides)%totalInfoSlides;updateSlider()}
function resetInterval(){clearInterval(interval);interval=setInterval(nextSlide,5000)}
infoNextBtn.addEventListener('click',()=>{nextSlide();resetInterval()});infoPrevBtn.addEventListener('click',()=>{prevSlide();resetInterval()});let startX=0;let isDragging=!1;const infoSliderContainer=document.getElementById('infoSliderContainer');infoSliderContainer.addEventListener('touchstart',(e)=>{startX=e.touches[0].clientX;isDragging=!0;clearInterval(interval)});infoSliderContainer.addEventListener('touchmove',(e)=>{if(!isDragging)return;const touchX=e.touches[0].clientX;const diff=touchX-startX;if(Math.abs(diff)>50){if(diff<0){nextSlide()}else{prevSlide()}
isDragging=!1}});infoSliderContainer.addEventListener('touchend',()=>{isDragging=!1;resetInterval()});const swiper=new Swiper(".mySwiper",{slidesPerView:"auto",spaceBetween:30,loop:!1,watchOverflow:!0,resistance:!1,allowTouchMove:!0,centeredSlides:!1,centeredSlidesBounds:!0,pagination:{el:".swiper-pagination",clickable:!0,},});function showViberMessage(){alert("Viber ထဲက Add Friend ထဲမှာ +66825502571 လို့ရိုက်ထည့်ပြီး Play with Thomas ကို Viber ကနေ ဆက်သွယ်နိုင်ပါတယ်။")}
document.addEventListener("DOMContentLoaded",()=>{const elements=document.querySelectorAll('.reveal-right');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('active');observer.unobserve(entry.target)}})},{threshold:0.1,rootMargin:"0px 0px -50px 0px"});elements.forEach(el=>observer.observe(el))});document.addEventListener("DOMContentLoaded",()=>{const elements=document.querySelectorAll('.reveal-up');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){requestAnimationFrame(()=>{entry.target.classList.add('active')});observer.unobserve(entry.target)}})},{threshold:0.1,rootMargin:"0px 0px -40px 0px"});elements.forEach(el=>observer.observe(el))})